// This file was automatically generated by make-pins.py
//
// --af boards/mk20dx256_af.csv
// --board boards/teensy/teensy_pins.csv
// --prefix boards/mk20dx256_prefix.c

// stm32fxx-prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>
#include <mk20dx128.h>

#include "py/obj.h"
#include "teensy_hal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .af_fn = (af_ptr) \
}

#define PIN(p_port, p_pin, p_num_af, p_af, p_adc_num, p_adc_channel) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_port ## p_pin, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (p_num_af), \
    .pin_mask = (1 << (p_pin)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
}

const pin_af_obj_t pin_E0_af[] = {
  //( 0, ADC     ,  1, SE4a      , ADC1    ), // ADC1_SE4a
  //( 1, PTE     ,  0,           , PTE0    ), // PTE0
  //( 2, SPI     ,  1, PCS1      , SPI1    ), // SPI1_PCS1
  AF( 3, UART    ,  1, TX        , UART1   ), // UART1_TX
  AF( 6, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
  //( 7, RTC     ,  0, CLKOUT    , RTC     ), // RTC_CLKOUT
};

const pin_obj_t pin_E0 = PIN(E, 0, 2, pin_E0_af, 0, 0);

const pin_af_obj_t pin_E1_af[] = {
  //( 0, ADC     ,  1, SE5a      , ADC1    ), // ADC1_SE5a
  //( 1, PTE     ,  1,           , PTE1    ), // PTE1
  //( 1, LLWU    ,  0, P0        , LLWU    ), // LLWU_P0
  //( 2, SPI     ,  1, SOUT      , SPI1    ), // SPI1_SOUT
  AF( 3, UART    ,  1, RX        , UART1   ), // UART1_RX
  AF( 6, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
  //( 7, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
};

const pin_obj_t pin_E1 = PIN(E, 1, 2, pin_E1_af, 0, 0);

// const pin_af_obj_t pin_Z0_af[] = {
  //( 0, PGA     ,  0, DP        , PGA0    ), // PGA0_DP
  //( 0, ADC     ,  0, DP0       , ADC0    ), // ADC0_DP0
  //( 0, ADC     ,  1, DP3       , ADC1    ), // ADC1_DP3
  //( 1, PTZ     ,  0,           , PTZ0    ), // PTZ0
// };

const pin_obj_t pin_Z0 = PIN(Z, 0, 0, NULL, 0, 0);

// const pin_af_obj_t pin_Z1_af[] = {
  //( 0, PGA     ,  0, DM        , PGA0    ), // PGA0_DM
  //( 0, ADC     ,  0, DM0       , ADC0    ), // ADC0_DM0
  //( 0, ADC     ,  1, DM3       , ADC1    ), // ADC1_DM3
  //( 1, PTZ     ,  1,           , PTZ1    ), // PTZ1
// };

const pin_obj_t pin_Z1 = PIN(Z, 1, 0, NULL, 0, 0);

// const pin_af_obj_t pin_Z2_af[] = {
  //( 0, PGA     ,  1, DP        , PGA1    ), // PGA1_DP
  //( 0, ADC     ,  1, DP0       , ADC1    ), // ADC1_DP0
  //( 0, ADC     ,  0, DP3       , ADC0    ), // ADC0_DP3
  //( 1, PTZ     ,  2,           , PTZ2    ), // PTZ2
// };

const pin_obj_t pin_Z2 = PIN(Z, 2, 0, NULL, 0, 0);

// const pin_af_obj_t pin_Z3_af[] = {
  //( 0, PGA     ,  1, DM        , PGA1    ), // PGA1_DM
  //( 0, ADC     ,  1, DM0       , ADC1    ), // ADC1_DM0
  //( 0, ADC     ,  0, DM3       , ADC0    ), // ADC0_DM3
  //( 1, PTZ     ,  3,           , PTZ3    ), // PTZ3
// };

const pin_obj_t pin_Z3 = PIN(Z, 3, 0, NULL, 0, 0);

// const pin_af_obj_t pin_Z5_af[] = {
  //( 0, DAC     ,  0, OUT       , DAC0    ), // DAC0_OUT
  //( 0, CMP     ,  1, IN3       , CMP1    ), // CMP1_IN3
  //( 0, ADC     ,  0, SE23      , ADC0    ), // ADC0_SE23
  //( 1, PTZ     ,  5,           , PTZ5    ), // PTZ5
// };

const pin_obj_t pin_Z5 = PIN(Z, 5, 0, NULL, 0, 0);

const pin_af_obj_t pin_A4_af[] = {
  //( 0, TSI     ,  0, CH5       , TSI0    ), // TSI0_CH5
  //( 1, PTA     ,  4,           , PTA4    ), // PTA4
  //( 1, LLWU    ,  0, P3        , LLWU    ), // LLWU_P3
  AF( 3, FTM     ,  0, CH1       , FTM0    ), // FTM0_CH1
  //( 6, NMI     ,  0, b         , NMI     ), // NMI_b
  //( 7, EZP     ,  0, CS_b      , EZP     ), // EZP_CS_b
};

const pin_obj_t pin_A4 = PIN(A, 4, 1, pin_A4_af, 0, 0);

const pin_af_obj_t pin_A5_af[] = {
  //( 1, PTA     ,  5,           , PTA5    ), // PTA5
  //( 2, USB     ,  0, CLKIN     , USB     ), // USB_CLKIN
  AF( 3, FTM     ,  0, CH2       , FTM0    ), // FTM0_CH2
  //( 5, CMP     ,  2, OUT       , CMP2    ), // CMP2_OUT
  //( 6, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
  //( 7, JTAG    ,  0, TRST_b    , JTAG    ), // JTAG_TRST_b
};

const pin_obj_t pin_A5 = PIN(A, 5, 1, pin_A5_af, 0, 0);

const pin_af_obj_t pin_A12_af[] = {
  //( 0, CMP     ,  2, IN0       , CMP2    ), // CMP2_IN0
  //( 1, PTA     , 12,           , PTA12   ), // PTA12
  //( 2, CAN     ,  0, TX        , CAN0    ), // CAN0_TX
  AF( 3, FTM     ,  1, CH0       , FTM1    ), // FTM1_CH0
  //( 6, I2S     ,  0, TXD0      , I2S0    ), // I2S0_TXD0
  AF( 7, FTM     ,  1, QD_PHA    , FTM1    ), // FTM1_QD_PHA
};

const pin_obj_t pin_A12 = PIN(A, 12, 2, pin_A12_af, 0, 0);

const pin_af_obj_t pin_A13_af[] = {
  //( 0, CMP     ,  2, IN1       , CMP2    ), // CMP2_IN1
  //( 1, PTA     , 13,           , PTA13   ), // PTA13
  //( 1, LLWU    ,  0, P4        , LLWU    ), // LLWU_P4
  //( 2, CAN     ,  0, RX        , CAN0    ), // CAN0_RX
  AF( 3, FTM     ,  1, CH1       , FTM1    ), // FTM1_CH1
  //( 6, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
  AF( 7, FTM     ,  1, QD_PHB    , FTM1    ), // FTM1_QD_PHB
};

const pin_obj_t pin_A13 = PIN(A, 13, 2, pin_A13_af, 0, 0);

const pin_af_obj_t pin_B0_af[] = {
  //( 0, ADC     ,  0, SE8       , ADC0    ), // ADC0_SE8
  //( 0, ADC     ,  1, SE8       , ADC1    ), // ADC1_SE8
  //( 0, TSI     ,  0, CH0       , TSI0    ), // TSI0_CH0
  //( 1, PTB     ,  0,           , PTB0    ), // PTB0
  //( 1, LLWU    ,  0, P5        , LLWU    ), // LLWU_P5
  AF( 2, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  AF( 3, FTM     ,  1, CH0       , FTM1    ), // FTM1_CH0
  AF( 6, FTM     ,  1, QD_PHA    , FTM1    ), // FTM1_QD_PHA
};

const pin_obj_t pin_B0 = PIN(B, 0, 3, pin_B0_af, 0, 0);

const pin_af_obj_t pin_B1_af[] = {
  //( 0, ADC     ,  0, SE9       , ADC0    ), // ADC0_SE9
  //( 0, ADC     ,  1, SE9       , ADC1    ), // ADC1_SE9
  //( 0, TSI     ,  0, CH6       , TSI0    ), // TSI0_CH6
  //( 1, PTB     ,  1,           , PTB1    ), // PTB1
  AF( 2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  AF( 3, FTM     ,  1, CH1       , FTM1    ), // FTM1_CH1
  AF( 6, FTM     ,  1, QD_PHB    , FTM1    ), // FTM1_QD_PHB
};

const pin_obj_t pin_B1 = PIN(B, 1, 3, pin_B1_af, 0, 0);

const pin_af_obj_t pin_B2_af[] = {
  //( 0, ADC     ,  0, SE12      , ADC0    ), // ADC0_SE12
  //( 0, TSI     ,  0, CH7       , TSI0    ), // TSI0_CH7
  //( 1, PTB     ,  2,           , PTB2    ), // PTB2
  AF( 2, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  //( 3, UART    ,  0, RTS_b     , UART0   ), // UART0_RTS_b
  //( 6, FTM     ,  0, FLT3      , FTM0    ), // FTM0_FLT3
};

const pin_obj_t pin_B2 = PIN(B, 2, 1, pin_B2_af, 0, 0);

const pin_af_obj_t pin_B3_af[] = {
  //( 0, ADC     ,  0, SE13      , ADC0    ), // ADC0_SE13
  //( 0, TSI     ,  0, CH8       , TSI0    ), // TSI0_CH8
  //( 1, PTB     ,  3,           , PTB3    ), // PTB3
  AF( 2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  //( 3, UART    ,  0, CTS_b     , UART0   ), // UART0_CTS_b
  //( 3, UART    ,  0, COL_b     , UART0   ), // UART0_COL_b
  //( 6, FTM     ,  0, FLT0      , FTM0    ), // FTM0_FLT0
};

const pin_obj_t pin_B3 = PIN(B, 3, 1, pin_B3_af, 0, 0);

const pin_af_obj_t pin_B16_af[] = {
  //( 0, TSI     ,  0, CH9       , TSI0    ), // TSI0_CH9
  //( 1, PTB     , 16,           , PTB16   ), // PTB16
  //( 2, SPI     ,  1, SOUT      , SPI1    ), // SPI1_SOUT
  AF( 3, UART    ,  0, RX        , UART0   ), // UART0_RX
  //( 5, FB      ,  0, AD17      , FB      ), // FB_AD17
  //( 6, EWM     ,  0, IN        , EWM     ), // EWM_IN
};

const pin_obj_t pin_B16 = PIN(B, 16, 1, pin_B16_af, 0, 0);

const pin_af_obj_t pin_B17_af[] = {
  //( 0, TSI     ,  0, CH10      , TSI0    ), // TSI0_CH10
  //( 1, PTB     , 17,           , PTB17   ), // PTB17
  //( 2, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
  AF( 3, UART    ,  0, TX        , UART0   ), // UART0_TX
  //( 5, FB      ,  0, AD16      , FB      ), // FB_AD16
  //( 6, EWM     ,  0, OUT_b     , EWM     ), // EWM_OUT_b
};

const pin_obj_t pin_B17 = PIN(B, 17, 1, pin_B17_af, 0, 0);

const pin_af_obj_t pin_B18_af[] = {
  //( 0, TSI     ,  0, CH11      , TSI0    ), // TSI0_CH11
  //( 1, PTB     , 18,           , PTB18   ), // PTB18
  //( 2, CAN     ,  0, TX        , CAN0    ), // CAN0_TX
  AF( 3, FTM     ,  2, CH0       , FTM2    ), // FTM2_CH0
  //( 4, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
  //( 5, FB      ,  0, AD15      , FB      ), // FB_AD15
  AF( 6, FTM     ,  2, QD_PHA    , FTM2    ), // FTM2_QD_PHA
};

const pin_obj_t pin_B18 = PIN(B, 18, 2, pin_B18_af, 0, 0);

const pin_af_obj_t pin_B19_af[] = {
  //( 0, TSI     ,  0, CH12      , TSI0    ), // TSI0_CH12
  //( 1, PTB     , 19,           , PTB19   ), // PTB19
  //( 2, CAN     ,  0, RX        , CAN0    ), // CAN0_RX
  AF( 3, FTM     ,  2, CH1       , FTM2    ), // FTM2_CH1
  //( 4, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
  //( 5, FB      ,  0, OE_b      , FB      ), // FB_OE_b
  AF( 6, FTM     ,  2, QD_PHB    , FTM2    ), // FTM2_QD_PHB
};

const pin_obj_t pin_B19 = PIN(B, 19, 2, pin_B19_af, 0, 0);

// const pin_af_obj_t pin_C0_af[] = {
  //( 0, ADC     ,  0, SE14      , ADC0    ), // ADC0_SE14
  //( 0, TSI     ,  0, CH13      , TSI0    ), // TSI0_CH13
  //( 1, PTC     ,  0,           , PTC0    ), // PTC0
  //( 2, SPI     ,  0, PCS4      , SPI0    ), // SPI0_PCS4
  //( 3, PDB     ,  0, EXTRG     , PDB0    ), // PDB0_EXTRG
  //( 5, FB      ,  0, AD14      , FB      ), // FB_AD14
  //( 6, I2S     ,  0, TXD1      , I2S0    ), // I2S0_TXD1
// };

const pin_obj_t pin_C0 = PIN(C, 0, 0, NULL, 0, 0);

const pin_af_obj_t pin_C1_af[] = {
  //( 0, ADC     ,  0, SE15      , ADC0    ), // ADC0_SE15
  //( 0, TSI     ,  0, CH14      , TSI0    ), // TSI0_CH14
  //( 1, PTC     ,  1,           , PTC1    ), // PTC1
  //( 1, LLWU    ,  0, P6        , LLWU    ), // LLWU_P6
  //( 2, SPI     ,  0, PCS3      , SPI0    ), // SPI0_PCS3
  //( 3, UART    ,  1, RTS_b     , UART1   ), // UART1_RTS_b
  AF( 4, FTM     ,  0, CH0       , FTM0    ), // FTM0_CH0
  //( 5, FB      ,  0, AD13      , FB      ), // FB_AD13
  //( 6, I2S     ,  0, TXD0      , I2S0    ), // I2S0_TXD0
};

const pin_obj_t pin_C1 = PIN(C, 1, 1, pin_C1_af, 0, 0);

const pin_af_obj_t pin_C2_af[] = {
  //( 0, ADC     ,  0, SE4b      , ADC0    ), // ADC0_SE4b
  //( 0, CMP     ,  1, IN0       , CMP1    ), // CMP1_IN0
  //( 0, TSI     ,  0, CH15      , TSI0    ), // TSI0_CH15
  //( 1, PTC     ,  2,           , PTC2    ), // PTC2
  //( 2, SPI     ,  0, PCS2      , SPI0    ), // SPI0_PCS2
  //( 3, UART    ,  1, CTS_b     , UART1   ), // UART1_CTS_b
  AF( 4, FTM     ,  0, CH1       , FTM0    ), // FTM0_CH1
  //( 5, FB      ,  0, AD12      , FB      ), // FB_AD12
  //( 6, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
};

const pin_obj_t pin_C2 = PIN(C, 2, 1, pin_C2_af, 0, 0);

const pin_af_obj_t pin_C3_af[] = {
  //( 0, CMP     ,  1, IN1       , CMP1    ), // CMP1_IN1
  //( 1, PTC     ,  3,           , PTC3    ), // PTC3
  //( 1, LLWU    ,  0, P7        , LLWU    ), // LLWU_P7
  //( 2, SPI     ,  0, PCS1      , SPI0    ), // SPI0_PCS1
  AF( 3, UART    ,  1, RX        , UART1   ), // UART1_RX
  AF( 4, FTM     ,  0, CH2       , FTM0    ), // FTM0_CH2
  //( 5, CLKOUT  ,  0,           , CLKOUT  ), // CLKOUT
  //( 6, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
};

const pin_obj_t pin_C3 = PIN(C, 3, 2, pin_C3_af, 0, 0);

const pin_af_obj_t pin_C4_af[] = {
  //( 1, PTC     ,  4,           , PTC4    ), // PTC4
  //( 1, LLWU    ,  0, P8        , LLWU    ), // LLWU_P8
  //( 2, SPI     ,  0, PCS0      , SPI0    ), // SPI0_PCS0
  AF( 3, UART    ,  1, TX        , UART1   ), // UART1_TX
  AF( 4, FTM     ,  0, CH3       , FTM0    ), // FTM0_CH3
  //( 5, FB      ,  0, AD11      , FB      ), // FB_AD11
  //( 6, CMP     ,  1, OUT       , CMP1    ), // CMP1_OUT
};

const pin_obj_t pin_C4 = PIN(C, 4, 2, pin_C4_af, 0, 0);

const pin_af_obj_t pin_C5_af[] = {
  //( 1, PTC     ,  5,           , PTC5    ), // PTC5
  //( 1, LLWU    ,  0, P9        , LLWU    ), // LLWU_P9
  AF( 2, SPI     ,  0, SCK       , SPI0    ), // SPI0_SCK
  //( 3, LPTMR   ,  0, ALT2      , LPTMR0  ), // LPTMR0_ALT2
  //( 4, I2S     ,  0, RXD0      , I2S0    ), // I2S0_RXD0
  //( 5, FB      ,  0, AD10      , FB      ), // FB_AD10
  //( 6, CMP     ,  0, OUT       , CMP0    ), // CMP0_OUT
};

const pin_obj_t pin_C5 = PIN(C, 5, 1, pin_C5_af, 0, 0);

// const pin_af_obj_t pin_C6_af[] = {
  //( 0, CMP     ,  0, IN0       , CMP0    ), // CMP0_IN0
  //( 1, PTC     ,  6,           , PTC6    ), // PTC6
  //( 1, LLWU    ,  0, P10       , LLWU    ), // LLWU_P10
  //( 2, SPI     ,  0, SOUT      , SPI0    ), // SPI0_SOUT
  //( 3, PDB     ,  0, EXTRG     , PDB0    ), // PDB0_EXTRG
  //( 4, I2S     ,  0, RX_BCLK   , I2S0    ), // I2S0_RX_BCLK
  //( 5, FB      ,  0, AD9       , FB      ), // FB_AD9
  //( 6, I2S     ,  0, MCLK      , I2S0    ), // I2S0_MCLK
// };

const pin_obj_t pin_C6 = PIN(C, 6, 0, NULL, 0, 0);

// const pin_af_obj_t pin_C7_af[] = {
  //( 0, CMP     ,  0, IN1       , CMP0    ), // CMP0_IN1
  //( 1, PTC     ,  7,           , PTC7    ), // PTC7
  //( 2, SPI     ,  0, SIN       , SPI0    ), // SPI0_SIN
  //( 3, USB     ,  0, SOF_OUT   , USB     ), // USB_SOF_OUT
  //( 4, I2S     ,  0, RX_FS     , I2S0    ), // I2S0_RX_FS
  //( 5, FB      ,  0, AD8       , FB      ), // FB_AD8
// };

const pin_obj_t pin_C7 = PIN(C, 7, 0, NULL, 0, 0);

// const pin_af_obj_t pin_C8_af[] = {
  //( 0, ADC     ,  1, SE4b      , ADC1    ), // ADC1_SE4b
  //( 0, CMP     ,  0, IN2       , CMP0    ), // CMP0_IN2
  //( 1, PTC     ,  8,           , PTC8    ), // PTC8
  //( 4, I2S     ,  0, MCLK      , I2S0    ), // I2S0_MCLK
  //( 5, FB      ,  0, AD7       , FB      ), // FB_AD7
// };

const pin_obj_t pin_C8 = PIN(C, 8, 0, NULL, 0, 0);

// const pin_af_obj_t pin_C9_af[] = {
  //( 0, ADC     ,  1, SE5b      , ADC1    ), // ADC1_SE5b
  //( 0, CMP     ,  0, IN3       , CMP0    ), // CMP0_IN3
  //( 1, PTC     ,  9,           , PTC9    ), // PTC9
  //( 4, I2S     ,  0, RX_BCLK   , I2S0    ), // I2S0_RX_BCLK
  //( 5, FB      ,  0, AD6       , FB      ), // FB_AD6
  //( 6, FTM     ,  2, FLT0      , FTM2    ), // FTM2_FLT0
// };

const pin_obj_t pin_C9 = PIN(C, 9, 0, NULL, 0, 0);

const pin_af_obj_t pin_C10_af[] = {
  //( 0, ADC     ,  1, SE6b      , ADC1    ), // ADC1_SE6b
  //( 1, PTC     , 10,           , PTC10   ), // PTC10
  AF( 2, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
  //( 4, I2S     ,  0, RX_FS     , I2S0    ), // I2S0_RX_FS
  //( 5, FB      ,  0, AD5       , FB      ), // FB_AD5
};

const pin_obj_t pin_C10 = PIN(C, 10, 1, pin_C10_af, 0, 0);

const pin_af_obj_t pin_C11_af[] = {
  //( 0, ADC     ,  1, SE7b      , ADC1    ), // ADC1_SE7b
  //( 1, PTC     , 11,           , PTC11   ), // PTC11
  //( 1, LLWU    ,  0, P11       , LLWU    ), // LLWU_P11
  AF( 2, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
  //( 4, I2S     ,  0, RXD1      , I2S0    ), // I2S0_RXD1
  //( 5, FB      ,  0, RW_b      , FB      ), // FB_RW_b
};

const pin_obj_t pin_C11 = PIN(C, 11, 1, pin_C11_af, 0, 0);

// const pin_af_obj_t pin_D0_af[] = {
  //( 1, PTD     ,  0,           , PTD0    ), // PTD0
  //( 1, LLWU    ,  0, P12       , LLWU    ), // LLWU_P12
  //( 2, SPI     ,  0, PCS0      , SPI0    ), // SPI0_PCS0
  //( 3, UART    ,  2, RTS_b     , UART2   ), // UART2_RTS_b
  //( 5, FB      ,  0, ALE       , FB      ), // FB_ALE
  //( 5, FB      ,  0, CS1_b     , FB      ), // FB_CS1_b
  //( 5, FB      ,  0, TS_b      , FB      ), // FB_TS_b
// };

const pin_obj_t pin_D0 = PIN(D, 0, 0, NULL, 0, 0);

const pin_af_obj_t pin_D1_af[] = {
  //( 0, ADC     ,  0, SE5b      , ADC0    ), // ADC0_SE5b
  //( 1, PTD     ,  1,           , PTD1    ), // PTD1
  AF( 2, SPI     ,  0, SCK       , SPI0    ), // SPI0_SCK
  //( 3, UART    ,  2, CTS_b     , UART2   ), // UART2_CTS_b
  //( 5, FB      ,  0, CS0_b     , FB      ), // FB_CS0_b
};

const pin_obj_t pin_D1 = PIN(D, 1, 1, pin_D1_af, 0, 0);

const pin_af_obj_t pin_D2_af[] = {
  //( 1, PTD     ,  2,           , PTD2    ), // PTD2
  //( 1, LLWU    ,  0, P13       , LLWU    ), // LLWU_P13
  //( 2, SPI     ,  0, SOUT      , SPI0    ), // SPI0_SOUT
  AF( 3, UART    ,  2, RX        , UART2   ), // UART2_RX
  //( 5, FB      ,  0, AD4       , FB      ), // FB_AD4
};

const pin_obj_t pin_D2 = PIN(D, 2, 1, pin_D2_af, 0, 0);

const pin_af_obj_t pin_D3_af[] = {
  //( 1, PTD     ,  3,           , PTD3    ), // PTD3
  //( 2, SPI     ,  0, SIN       , SPI0    ), // SPI0_SIN
  AF( 3, UART    ,  2, TX        , UART2   ), // UART2_TX
  //( 5, FB      ,  0, AD3       , FB      ), // FB_AD3
};

const pin_obj_t pin_D3 = PIN(D, 3, 1, pin_D3_af, 0, 0);

const pin_af_obj_t pin_D4_af[] = {
  //( 1, PTD     ,  4,           , PTD4    ), // PTD4
  //( 1, LLWU    ,  0, P14       , LLWU    ), // LLWU_P14
  //( 2, SPI     ,  0, PCS1      , SPI0    ), // SPI0_PCS1
  //( 3, UART    ,  0, RTS_b     , UART0   ), // UART0_RTS_b
  AF( 4, FTM     ,  0, CH4       , FTM0    ), // FTM0_CH4
  //( 5, FB      ,  0, AD2       , FB      ), // FB_AD2
  //( 6, EWM     ,  0, IN        , EWM     ), // EWM_IN
};

const pin_obj_t pin_D4 = PIN(D, 4, 1, pin_D4_af, 0, 0);

const pin_af_obj_t pin_D5_af[] = {
  //( 0, ADC     ,  0, SE6b      , ADC0    ), // ADC0_SE6b
  //( 1, PTD     ,  5,           , PTD5    ), // PTD5
  //( 2, SPI     ,  0, PCS2      , SPI0    ), // SPI0_PCS2
  //( 3, UART    ,  0, CTS_b     , UART0   ), // UART0_CTS_b
  //( 3, UART    ,  0, COL_b     , UART0   ), // UART0_COL_b
  AF( 4, FTM     ,  0, CH5       , FTM0    ), // FTM0_CH5
  //( 5, FB      ,  0, AD1       , FB      ), // FB_AD1
  //( 6, EWM     ,  0, OUT_b     , EWM     ), // EWM_OUT_b
};

const pin_obj_t pin_D5 = PIN(D, 5, 1, pin_D5_af, 0, 0);

const pin_af_obj_t pin_D6_af[] = {
  //( 0, ADC     ,  0, SE7b      , ADC0    ), // ADC0_SE7b
  //( 1, PTD     ,  6,           , PTD6    ), // PTD6
  //( 1, LLWU    ,  0, P15       , LLWU    ), // LLWU_P15
  //( 2, SPI     ,  0, PCS3      , SPI0    ), // SPI0_PCS3
  AF( 3, UART    ,  0, RX        , UART0   ), // UART0_RX
  AF( 4, FTM     ,  0, CH6       , FTM0    ), // FTM0_CH6
  //( 5, FB      ,  0, AD0       , FB      ), // FB_AD0
  //( 6, FTM     ,  0, FLT0f     , FTM0    ), // FTM0_FLT0f
};

const pin_obj_t pin_D6 = PIN(D, 6, 2, pin_D6_af, 0, 0);

const pin_af_obj_t pin_D7_af[] = {
  //( 1, PTD     ,  7,           , PTD7    ), // PTD7
  //( 2, CMT     ,  0, IRO       , CMT     ), // CMT_IRO
  AF( 3, UART    ,  0, TX        , UART0   ), // UART0_TX
  AF( 4, FTM     ,  0, CH7       , FTM0    ), // FTM0_CH7
  //( 6, FTM     ,  0, FLT1      , FTM0    ), // FTM0_FLT1
};

const pin_obj_t pin_D7 = PIN(D, 7, 2, pin_D7_af, 0, 0);

STATIC const mp_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_OBJ_NEW_QSTR(MP_QSTR_E0), (mp_obj_t)&pin_E0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_E1), (mp_obj_t)&pin_E1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z0), (mp_obj_t)&pin_Z0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z1), (mp_obj_t)&pin_Z1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z2), (mp_obj_t)&pin_Z2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z3), (mp_obj_t)&pin_Z3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_Z5), (mp_obj_t)&pin_Z5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A4), (mp_obj_t)&pin_A4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A5), (mp_obj_t)&pin_A5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A12), (mp_obj_t)&pin_A12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A13), (mp_obj_t)&pin_A13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B0), (mp_obj_t)&pin_B0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B1), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B2), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B3), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B16), (mp_obj_t)&pin_B16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B17), (mp_obj_t)&pin_B17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B18), (mp_obj_t)&pin_B18 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B19), (mp_obj_t)&pin_B19 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C0), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C1), (mp_obj_t)&pin_C1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C2), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C3), (mp_obj_t)&pin_C3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C4), (mp_obj_t)&pin_C4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C5), (mp_obj_t)&pin_C5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C6), (mp_obj_t)&pin_C6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C7), (mp_obj_t)&pin_C7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C8), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C9), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C10), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C11), (mp_obj_t)&pin_C11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D0), (mp_obj_t)&pin_D0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D1), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D2), (mp_obj_t)&pin_D2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D3), (mp_obj_t)&pin_D3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D4), (mp_obj_t)&pin_D4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D5), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D6), (mp_obj_t)&pin_D6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D7), (mp_obj_t)&pin_D7 },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_OBJ_NEW_QSTR(MP_QSTR_D0), (mp_obj_t)&pin_B16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D1), (mp_obj_t)&pin_B17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D2), (mp_obj_t)&pin_D0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D3), (mp_obj_t)&pin_A12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D4), (mp_obj_t)&pin_A13 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D5), (mp_obj_t)&pin_D7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D6), (mp_obj_t)&pin_D4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D7), (mp_obj_t)&pin_D2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D8), (mp_obj_t)&pin_D3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D9), (mp_obj_t)&pin_C3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D10), (mp_obj_t)&pin_C4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D11), (mp_obj_t)&pin_C6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D12), (mp_obj_t)&pin_C7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D13), (mp_obj_t)&pin_C5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D14), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D15), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D16), (mp_obj_t)&pin_B0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D17), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D18), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D19), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D20), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D21), (mp_obj_t)&pin_D6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D22), (mp_obj_t)&pin_C1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D23), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D24), (mp_obj_t)&pin_A5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D25), (mp_obj_t)&pin_B19 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D26), (mp_obj_t)&pin_E1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D27), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D28), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D29), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D30), (mp_obj_t)&pin_C11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D31), (mp_obj_t)&pin_E0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D32), (mp_obj_t)&pin_B18 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D33), (mp_obj_t)&pin_A4 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A0), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A1), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A2), (mp_obj_t)&pin_B0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A3), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A4), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A5), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A6), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A7), (mp_obj_t)&pin_D6 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A8), (mp_obj_t)&pin_C1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A9), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A10), (mp_obj_t)&pin_Z0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A11), (mp_obj_t)&pin_Z1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A12), (mp_obj_t)&pin_Z2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A13), (mp_obj_t)&pin_Z3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A14), (mp_obj_t)&pin_Z5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A15), (mp_obj_t)&pin_E1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A16), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A17), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A18), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A19), (mp_obj_t)&pin_C11 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A20), (mp_obj_t)&pin_E0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_LED), (mp_obj_t)&pin_C5 },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
};

const pin_obj_t * const pin_adc2[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
};

const pin_obj_t * const pin_adc3[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
};
