// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.8.6-552-g3fcb6e70-dirty"
#define MICROPY_GIT_HASH "3fcb6e70-dirty"
#define MICROPY_BUILD_DATE "2022-10-20"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (8)
#define MICROPY_VERSION_MICRO (6)
#define MICROPY_VERSION_STRING "1.8.6"
