// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "56920241-dirty"
#define MICROPY_GIT_HASH "56920241-dirty"
#define MICROPY_BUILD_DATE "2026-06-04"
#define MICROPY_VERSION_MAJOR (0)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (1)
#define MICROPY_VERSION_STRING "0.0.1"
